# Generated by Django 6.0.6 on 2026-06-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secao', models.CharField(choices=[('hero', 'Hero'), ('sobre', 'Sobre'), ('atuacao', 'Atuação'), ('diferenciais', 'Diferenciais'), ('contato', 'Contato')], max_length=20, verbose_name='Seção')),
                ('chave', models.CharField(help_text='Identificador interno (ex: hero_titulo)', max_length=100, unique=True, verbose_name='Chave')),
                ('titulo', models.CharField(blank=True, max_length=500, verbose_name='Título / texto curto')),
                ('texto', models.TextField(blank=True, verbose_name='Texto longo')),
                ('imagem', models.ImageField(blank=True, upload_to='site/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Conteúdo do Site',
                'verbose_name_plural': 'Conteúdos do Site',
                'ordering': ['secao', 'chave'],
            },
        ),
    ]
