# Generated by Django 6.0.6 on 2026-06-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudosite',
            name='video',
            field=models.FileField(blank=True, upload_to='site/videos/', verbose_name='Vídeo'),
        ),
        migrations.AlterField(
            model_name='conteudosite',
            name='chave',
            field=models.CharField(max_length=100, unique=True, verbose_name='Chave'),
        ),
        migrations.AlterField(
            model_name='conteudosite',
            name='titulo',
            field=models.CharField(blank=True, max_length=500, verbose_name='Texto curto'),
        ),
    ]
