# Generated by Django 6.0.6 on 2026-06-26 12:30

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_conteudosite_video_alter_conteudosite_chave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudosite',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=core.models._upload_imagem, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='conteudosite',
            name='video',
            field=models.FileField(blank=True, max_length=255, upload_to=core.models._upload_video, verbose_name='Vídeo'),
        ),
    ]
