# Generated by Django 6.0.6 on 2026-06-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('resumo', models.TextField(help_text='Aparece na listagem do blog', verbose_name='Resumo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('imagem_capa', models.ImageField(blank=True, upload_to='blog/', verbose_name='Imagem de capa')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
